services:
  nestjs-boilerplate-api:
    image: nestjs-boilerplate-api
    container_name: nestjs-boilerplate-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    networks:
      - nestjs-boilerplate-network

  db:
    image: postgres:16
    container_name: nestjs-boilerplate-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'UTC'
    ports:
      - '25432:5432'
    networks:
      - nestjs-boilerplate-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass redispass'
    networks:
      - nestjs-boilerplate-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - '${MAIL_CLIENT_PORT}:8025' # Web UI
      - '${MAIL_PORT}:1025' # SMTP
    environment:
      MP_MAX_MESSAGES: 5000
    networks:
      - nestjs-boilerplate-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '18080:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    networks:
      - nestjs-boilerplate-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  minio_data:

networks:
  nestjs-boilerplate-network:
    driver: bridge
